export const PRODUCTS = [
  {
    id: 1,
    name: 'Soil Maps',
    shortName: 'SoilMaps',
    icon: '🗺️',
    emoji: '🌍',
    color: '#22C55E',
    bgColor: '#0A2010',
    description: 'Real-time soil health mapping with GPS-tagged data points across your farmland.',
    category: 'Mapping',
    tag: 'Precision Agriculture',
    active: true,
  },
  {
    id: 2,
    name: 'Ph Bottle',
    shortName: 'PhBottle',
    icon: '🧪',
    emoji: '⚗️',
    color: '#F59E0B',
    bgColor: '#1A1500',
    description: 'Portable pH testing kit with reagent-based colorimetric analysis for field use.',
    category: 'Testing',
    tag: 'Field Kit',
    active: true,
  },
  {
    id: 3,
    name: 'SOILENZ',
    shortName: 'SOILENZ',
    icon: '🔬',
    emoji: '⚡',
    color: '#22C55E',
    bgColor: '#0A2010',
    description: 'Advanced BLE soil analyzer measuring pH, EC, N, P, K with instant recommendations.',
    category: 'Analysis',
    tag: 'Smart Device',
    active: true,
    isMain: true,
  },
  {
    id: 4,
    name: 'SoilSparsh',
    shortName: 'SoilSparsh',
    icon: '✋',
    emoji: '🌱',
    color: '#4ADE80',
    bgColor: '#091A0C',
    description: 'Haptic feedback soil sensor — feel the soil health through vibration patterns.',
    category: 'Sensing',
    tag: 'Innovative',
    active: true,
  },
  {
    id: 5,
    name: 'SOILIFE',
    shortName: 'SOILIFE',
    icon: '🦠',
    emoji: '🌿',
    color: '#34D399',
    bgColor: '#061410',
    description: 'Microbial activity monitoring for soil health — measure living soil ecosystem.',
    category: 'Biology',
    tag: 'Soil Biology',
    active: false,
  },
  {
    id: 6,
    name: 'Leaf Lenz',
    shortName: 'LeafLenz',
    icon: '🍃',
    emoji: '📷',
    color: '#86EFAC',
    bgColor: '#081210',
    description: 'AI-powered leaf disease detection using smartphone camera — instant diagnosis.',
    category: 'Plant Health',
    tag: 'AI Vision',
    active: true,
  },
  {
    id: 7,
    name: 'AI Agronomy',
    shortName: 'AIAgronomy',
    icon: '🤖',
    emoji: '🧠',
    color: '#818CF8',
    bgColor: '#0D0C20',
    description: 'GPT-powered agronomist chatbot — ask crop questions and get expert advice 24/7.',
    category: 'AI',
    tag: 'AI Advisor',
    active: true,
  },
  {
    id: 8,
    name: 'Crop Recommend',
    shortName: 'CropRec',
    icon: '🌾',
    emoji: '📊',
    color: '#FCD34D',
    bgColor: '#1A1200',
    description: 'Data-driven crop selection based on soil analysis, climate, and market pricing.',
    category: 'Planning',
    tag: 'Smart Planning',
    active: true,
  },
  {
    id: 9,
    name: 'Carbon Monitor',
    shortName: 'CarbonMon',
    icon: '♻️',
    emoji: '🌡️',
    color: '#6EE7B7',
    bgColor: '#061412',
    description: 'Track soil carbon sequestration to earn carbon credits and improve soil health.',
    category: 'Environment',
    tag: 'Carbon Credits',
    active: false,
  },
  {
    id: 10,
    name: 'Water Testing',
    shortName: 'WaterTest',
    icon: '💧',
    emoji: '🚰',
    color: '#38BDF8',
    bgColor: '#060C16',
    description: 'Irrigation water quality analysis — pH, TDS, hardness, and contaminant detection.',
    category: 'Water',
    tag: 'Water Quality',
    active: true,
  },
];