// src/screens/partner/partnerConstants.js
// ─────────────────────────────────────────────────────────────────────────────
// SHARED CONSTANTS, DATA SHAPES, AND MOCK DATA FOR SOIL PARTNER MODULE
// Replace mock data with Redux selectors / API calls in production
// ─────────────────────────────────────────────────────────────────────────────

export const INDIA_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];

export const TRAINING_ITEMS = [
  { key: 'app', label: 'App Training', icon: '📱' },
  { key: 'device', label: 'Device Training', icon: '🔬' },
  { key: 'sampling', label: 'Sampling Training', icon: '🧪' },
  { key: 'farmer', label: 'Farmer Communication Training', icon: '🌾' },
  { key: 'payment', label: 'Payment Training', icon: '💳' },
];

export const MENU_ITEMS = [
  {
    key: 'villages',
    icon: '🏘️',
    label: 'My Villages',
    color: '#22C55E',
    screen: 'PartnerVillages',
  },
  {
    key: 'register',
    icon: '👨‍🌾',
    label: 'Register Farmer',
    color: '#3B82F6',
    screen: 'RegisterFarmer',
  },
  {
    key: 'sample',
    icon: '🧪',
    label: 'Collect Sample',
    color: '#F59E0B',
    screen: 'CollectSample',
  },
  {
    key: 'track',
    icon: '📦',
    label: 'Track Samples',
    color: '#A78BFA',
    screen: 'TrackSamples',
  },
  {
    key: 'testing',
    icon: '🔬',
    label: 'Testing Status',
    color: '#F97316',
    screen: 'TestingStatus',
  },
  {
    key: 'reports',
    icon: '📄',
    label: 'Reports',
    color: '#22C55E',
    screen: 'PartnerReports',
  },
  {
    key: 'payments',
    icon: '💰',
    label: 'Payments',
    color: '#FBBF24',
    screen: 'PartnerPayments',
  },
  {
    key: 'marketplace',
    icon: '🛒',
    label: 'Marketplace',
    color: '#EC4899',
    screen: 'Marketplace',
  },
  {
    key: 'training',
    icon: '🎓',
    label: 'Training Videos',
    color: '#3B82F6',
    screen: 'TrainingVideos',
  },
  {
    key: 'support',
    icon: '🆘',
    label: 'Support',
    color: '#F87171',
    screen: 'PartnerSupport',
  },
];

export const FARMER_STATUSES = [
  { key: 'lead', label: 'Lead', color: '#94A3B8', icon: '📋' },
  { key: 'registered', label: 'Registered', color: '#3B82F6', icon: '✅' },
  { key: 'pending', label: 'Sample Pending', color: '#F59E0B', icon: '⏳' },
  { key: 'collected', label: 'Sample Collected', color: '#F97316', icon: '📦' },
  { key: 'testing', label: 'Testing Done', color: '#A78BFA', icon: '🔬' },
  { key: 'delivered', label: 'Report Delivered', color: '#22C55E', icon: '📄' },
  { key: 'repeat', label: 'Repeat Customer', color: '#FBBF24', icon: '⭐' },
];

export const SAMPLE_LIFECYCLE = [
  { key: 'collected', label: 'Collected', icon: '🧪' },
  { key: 'packed', label: 'Packed', icon: '📦' },
  { key: 'sent', label: 'Sent', icon: '🚚' },
  { key: 'received', label: 'Received', icon: '📬' },
  { key: 'tested', label: 'Tested', icon: '🔬' },
  { key: 'advisory_ready', label: 'Advisory Ready', icon: '📋' },
  { key: 'delivered', label: 'Delivered', icon: '✅' },
];

export const CROPS = [
  'Rice',
  'Wheat',
  'Maize',
  'Cotton',
  'Sugarcane',
  'Soybean',
  'Groundnut',
  'Sunflower',
  'Barley',
  'Jowar',
  'Bajra',
  'Tomato',
  'Onion',
  'Potato',
  'Arabica Coffee',
  'Robusta Coffee',
  'Turmeric',
  'Ginger',
  'Chilli',
];

export const SEASONS = [
  'Kharif (Jun–Oct)',
  'Rabi (Nov–Mar)',
  'Zaid (Mar–Jun)',
  'Year Round',
];

// ── MOCK PARTNER DATA ──────────────────────────────────────────────────────
export const MOCK_PARTNER = {
  id: 'SP-2025-0142',
  name: 'Ravi Kumar',
  mobile: '9876543210',
  aadhaar: '234567890123',
  village: 'Koppal',
  district: 'Koppal',
  state: 'Karnataka',
  farmerNetwork: 142,
  activeVillages: 8,
  joined: 'Jan 2025',
  coverageRadius: 20,
  training: {
    app: true,
    device: true,
    sampling: true,
    farmer: true,
    payment: true,
  },
};

export const MOCK_VILLAGES = [
  {
    id: 'v1',
    name: 'Koppal',
    farmers: 28,
    samples: 12,
    covered: true,
    lat: 15.3542,
    lng: 76.1549,
  },
  {
    id: 'v2',
    name: 'Yadgir',
    farmers: 19,
    samples: 8,
    covered: true,
    lat: 16.7702,
    lng: 77.1397,
  },
  {
    id: 'v3',
    name: 'Gangavati',
    farmers: 22,
    samples: 9,
    covered: true,
    lat: 15.4303,
    lng: 76.5339,
  },
  {
    id: 'v4',
    name: 'Kushtagi',
    farmers: 14,
    samples: 5,
    covered: false,
    lat: 15.7604,
    lng: 76.189,
  },
  {
    id: 'v5',
    name: 'Mundargi',
    farmers: 11,
    samples: 4,
    covered: true,
    lat: 15.2085,
    lng: 75.8841,
  },
  {
    id: 'v6',
    name: 'Gadag',
    farmers: 8,
    samples: 2,
    covered: false,
    lat: 15.4166,
    lng: 75.6281,
  },
  {
    id: 'v7',
    name: 'Ron',
    farmers: 6,
    samples: 1,
    covered: false,
    lat: 15.6975,
    lng: 75.7217,
  },
  {
    id: 'v8',
    name: 'Shirahatti',
    farmers: 9,
    samples: 3,
    covered: true,
    lat: 15.235,
    lng: 75.927,
  },
];

export const MOCK_FARMERS = [
  {
    id: 'F001',
    name: 'Mahesh Patil',
    mobile: '9812345678',
    village: 'Koppal',
    land: 3.5,
    crop: 'Cotton',
    season: 'Kharif (Jun–Oct)',
    status: 'delivered',
    lat: 15.3542,
    lng: 76.1549,
    registered: '2025-01-15',
  },
  {
    id: 'F002',
    name: 'Raju Reddy',
    mobile: '9823456789',
    village: 'Yadgir',
    land: 2.0,
    crop: 'Rice',
    season: 'Kharif (Jun–Oct)',
    status: 'collected',
    lat: 16.7702,
    lng: 77.1397,
    registered: '2025-02-10',
  },
  {
    id: 'F003',
    name: 'Suresh Naik',
    mobile: '9834567890',
    village: 'Gangavati',
    land: 5.0,
    crop: 'Sugarcane',
    season: 'Year Round',
    status: 'testing',
    lat: 15.4303,
    lng: 76.5339,
    registered: '2025-01-28',
  },
  {
    id: 'F004',
    name: 'Basappa Goud',
    mobile: '9845678901',
    village: 'Koppal',
    land: 1.5,
    crop: 'Wheat',
    season: 'Rabi (Nov–Mar)',
    status: 'repeat',
    lat: 15.3542,
    lng: 76.1549,
    registered: '2024-11-05',
  },
  {
    id: 'F005',
    name: 'Venkat Rao',
    mobile: '9856789012',
    village: 'Kushtagi',
    land: 4.0,
    crop: 'Maize',
    season: 'Kharif (Jun–Oct)',
    status: 'pending',
    lat: 15.7604,
    lng: 76.189,
    registered: '2025-02-20',
  },
  {
    id: 'F006',
    name: 'Hanumappa K',
    mobile: '9867890123',
    village: 'Mundargi',
    land: 2.5,
    crop: 'Jowar',
    season: 'Rabi (Nov–Mar)',
    status: 'registered',
    lat: 15.2085,
    lng: 75.8841,
    registered: '2025-03-01',
  },
  {
    id: 'F007',
    name: 'Shivappa M',
    mobile: '9878901234',
    village: 'Koppal',
    land: 3.0,
    crop: 'Groundnut',
    season: 'Kharif (Jun–Oct)',
    status: 'lead',
    lat: 15.3542,
    lng: 76.1549,
    registered: '2025-03-05',
  },
];

export const MOCK_SAMPLES = [
  {
    id: 'SS-2025-001',
    farmerId: 'F001',
    farmer: 'Mahesh Patil',
    village: 'Koppal',
    status: 'delivered',
    date: '2025-03-10',
    operatorId: 'SP-2025-0142',
  },
  {
    id: 'SS-2025-002',
    farmerId: 'F002',
    farmer: 'Raju Reddy',
    village: 'Yadgir',
    status: 'collected',
    date: '2025-03-12',
    operatorId: 'SP-2025-0142',
  },
  {
    id: 'SS-2025-003',
    farmerId: 'F003',
    farmer: 'Suresh Naik',
    village: 'Gangavati',
    status: 'advisory_ready',
    date: '2025-03-11',
    operatorId: 'SP-2025-0142',
  },
  {
    id: 'SS-2025-004',
    farmerId: 'F004',
    farmer: 'Basappa Goud',
    village: 'Koppal',
    status: 'delivered',
    date: '2025-03-09',
    operatorId: 'SP-2025-0142',
  },
  {
    id: 'SS-2025-005',
    farmerId: 'F005',
    farmer: 'Venkat Rao',
    village: 'Kushtagi',
    status: 'sent',
    date: '2025-03-13',
    operatorId: 'SP-2025-0142',
  },
  {
    id: 'SS-2025-006',
    farmerId: 'F006',
    farmer: 'Hanumappa K',
    village: 'Mundargi',
    status: 'received',
    date: '2025-03-13',
    operatorId: 'SP-2025-0142',
  },
  {
    id: 'SS-2025-007',
    farmerId: 'F007',
    farmer: 'Shivappa M',
    village: 'Koppal',
    status: 'tested',
    date: '2025-03-14',
    operatorId: 'SP-2025-0142',
  },
];

export const MOCK_PAYMENTS = {
  today: {
    soil: 800,
    device: 0,
    commission: 200,
    subscription: 0,
    total: 1000,
  },
  week: {
    soil: 4200,
    device: 1500,
    commission: 950,
    subscription: 500,
    total: 7150,
  },
  month: {
    soil: 9800,
    device: 4200,
    commission: 2100,
    subscription: 1500,
    total: 17600,
  },
};

export const MOCK_KPI = {
  today: { collected: 4, tested: 2, pending: 7, delivered: 3 },
  monthly: {
    samples: 38,
    samplesTarget: 60,
    farmers: 21,
    farmersTarget: 30,
    revenue: 11400,
    revenueTarget: 18000,
  },
  allTime: {
    farmers: 142,
    villages: 8,
    tests: 284,
    reports: 271,
    revenue: 142000,
    repeat: 48,
  },
  performance: { activity: 82, revenue: 63, satisfaction: 91 },
};

export const INCENTIVE_STRUCTURE = [
  { label: 'Per farmer registered', value: '₹50' },
  { label: 'Per sample collected', value: '₹30' },
  { label: 'Per sample tested', value: '₹20' },
  { label: 'Per report delivered', value: '₹25' },
  { label: 'Per repeat farmer', value: '₹40' },
  { label: 'Per product sold', value: '2–5%' },
];
